compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  midnight-ntwrk:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.11.0.cjs
