name: Setup Node Environment
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version-file: '.tool-versions'
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'

    - name: Install dependencies
      shell: bash
      run: yarn install
