name: Lint & Build

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['main']

permissions: {}

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Setup Node Environment
        uses: ./.github/workflows/setup-env

      - name: Run lint
        run: yarn lint

      - name: Run build
        run: yarn build
